"""add synthetic and onboarding columns

Revision ID: 4fb6f2ebf8c2
Revises: 008_add_course_skills
Create Date: 2026-04-05 19:48:35.116004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fb6f2ebf8c2'
down_revision = '008_add_course_skills'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('skills')

    with op.batch_alter_table('program_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_courses_course_id'))
        batch_op.drop_index(batch_op.f('ix_program_courses_program_id'))

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('concentrations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('learning_outcomes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('admission_requirements',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('special_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_programs_admission_requirements'), postgresql_ops={'admission_requirements': 'jsonb_path_ops'}, postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_programs_requirements'), postgresql_ops={'requirements': 'jsonb_path_ops'}, postgresql_using='gin')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('is_synthetic',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_column('target_job_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_job_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.alter_column('onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_synthetic',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_requirements'), ['requirements'], unique=False, postgresql_ops={'requirements': 'jsonb_path_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_programs_admission_requirements'), ['admission_requirements'], unique=False, postgresql_ops={'admission_requirements': 'jsonb_path_ops'}, postgresql_using='gin')
        batch_op.alter_column('special_features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('admission_requirements',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('learning_outcomes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('concentrations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('requirements',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('program_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_courses_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_program_courses_course_id'), ['course_id'], unique=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
